### ISSUE TITLE
resfinder component

### ISSUE THREAD

**Issue by ghost** [ssi-dk/bifrost-cge_resfinder#7]

**Comment by ghost** [comment]
The component is one Computerome, but we haven't tested it, so we don't know what the status is.
According to the repository Lars has made some changes to the component recently and bumped the version number from 2.2.2 to 2.2.3.

**Comment by githubz0r** [comment]
Also FYI the v3 tag is an older version made by me when I was still a noob. 
Expecting this to be done next week after our meeting with some end users.
